ci/recipe/meta.yaml
install-pplacer.sh

Adjusts the pplacer installation script to use the `PREFIX` env variable when available (i.e., during conda builds) or `CONDA_PREFIX` when installing in an existing, activated conda environment.

FIX: correctly install pplacer during conda build

---

q2_moshpit/plugin_setup.py

This PR updates the import of FeatureMap to originate from q2-types, accompanying this https://github.com/qiime2/q2-types/pull/303 which adds FeatureMap and associated formats to q2-types for use in q2-vsearch. This PR should not be merged until q2-types #303 has been merged.

IMP: updates FeatureMap import for q2-types migration

---

q2_moshpit/busco/tests/data/plot_as_dict.json
q2_moshpit/busco/tests/test_utils.py

**Closes #81**
In `busco/tests/test_utils.py` the `test_draw_busco_plots_for_render` function compares two dictionaries. Some of the entries in this dictionary change depending on the version of `altair` that is being used. I removed and edited these version-dependent keys to bypass the test failure. The rest of the dictionary is still compared.

BUG: test_draw_busco_plots_for_render is altair version variant

---

q2_moshpit/busco/tests/data/plot_as_dict.json
q2_moshpit/busco/tests/test_utils.py
q2_moshpit/busco/utils.py

**Closes #78**
- Controls the height of the plot by assigning a constant height to each bar.
- Controls the vertical spacing between subgraphs.
- Adjusts tests and calls to this function accordingly.

ENH: Busco main plot. Bars with constant height.

---

q2_moshpit/busco/tests/data/plot_as_dict.json
q2_moshpit/busco/utils.py

**Closes #84**
-  Eliminates MAG ID titles from y-axis to avoid misaligned plots

BUG: Eliminate MAG ID from y-axis to avoid misaligned plots

---

q2_moshpit/plugin_setup.py

This PR removes a duplicate entry for the `fetch-kaiju-db` action from `plugin_setupy.py`.

FIX: remove duplicated action registration

---

q2_moshpit/busco/busco.py
q2_moshpit/plugin_setup.py

- Removes useless parameters from action `evaluate-busco`
- Closes #113 
- Not blocked by anything 🥳 
```bash
export MY_OS="osx" 
wget "https://data.qiime2.org/distro/shotgun/qiime2-shotgun-2023.9-py38-"$MY_OS"-conda.yml"
conda env create -n q2-shotgun --file qiime2-shotgun-2023.9-py38-osx-conda.yml
rm "qiime2-shotgun-2023.9-py38-"$MY_OS"-conda.yml"
```
1. Clone the repo and checkout the PR branch (skip this step if you already have a local copy of the code):
```bash
conda activate q2-shotgun
conda remove q2-moshpit
git clone git@github.com:bokulich-lab/q2-moshpit.git
cd q2-moshpit
gh pr checkout 121
pip install -e .
```
3. Test it out!
```bash
qiime dev refresh-cache
```
```bash
pytest -W ignore -vv --pyargs q2_moshpit
```

MAINT: clean up the input parameters to `evaluate-busco`

---

ci/recipe/meta.yaml
q2_moshpit/busco/busco.py
q2_moshpit/busco/tests/test_busco.py
q2_moshpit/busco/tests/test_utils.py
q2_moshpit/busco/utils.py
q2_moshpit/dereplication/derep.py
q2_moshpit/dereplication/tests/test_dereplication.py
q2_moshpit/eggnog/_dbs.py
q2_moshpit/eggnog/_method.py
q2_moshpit/eggnog/tests/test_dbs.py
q2_moshpit/eggnog/tests/test_method.py
q2_moshpit/kaiju/classification.py
q2_moshpit/kaiju/database.py
q2_moshpit/kaiju/tests/test_database.py
q2_moshpit/kraken2/bracken.py
q2_moshpit/kraken2/classification.py
q2_moshpit/kraken2/database.py
q2_moshpit/kraken2/helpers.py
q2_moshpit/kraken2/select.py
q2_moshpit/kraken2/tests/test_bracken.py
q2_moshpit/kraken2/tests/test_classification.py
q2_moshpit/kraken2/tests/test_database.py
q2_moshpit/kraken2/tests/test_selection.py
q2_moshpit/metabat2/metabat2.py
q2_moshpit/metabat2/tests/test_metabat2.py
q2_moshpit/plugin_setup.py
q2_moshpit/prodigal/prodigal.py
q2_moshpit/prodigal/tests/test_prodigal.py

Change types_genomics to types in accordance with qiime2/q2-types#309
Blocked by qiime2/q2-types#309

No more types genomics

---

q2_moshpit/kraken2/helpers.py

@misialq pointed out that we shouldn't need to load things into dataframes when collating outputs and we should instead just be able to move the file. I believe he is correct with the current implementation of parallelization.

Just mv files, we should never need to collate multiple files for one sample/contig

---

q2_moshpit/eggnog/_method.py
q2_moshpit/plugin_setup.py

- The eggnog-annotate action wrapps the emapper.py script from eggnog to perform annotations.
- The emapper.py script allows users to specify the number of cpu's with the --cpu flag.
- However this parameter is not exposed in the eggnog-annotate action.
- This PR exposes the `--cpu` parameter such that users can use this functionality.
- Closes #135 
```bash
export MY_OS="osx" 
wget "https://data.qiime2.org/distro/shotgun/qiime2-shotgun-2023.9-py38-"$MY_OS"-conda.yml"
conda env create -n q2-shotgun --file qiime2-shotgun-2023.9-py38-osx-conda.yml
rm "qiime2-shotgun-2023.9-py38-"$MY_OS"-conda.yml"
```
Now clone the repo and checkout the PR branch (skip this step if you already have a local copy of the code):
```bash
conda activate q2-shotgun
conda remove q2-moshpit
git clone …
```

ENH: Expose `cpu` param in `eggnog-annotate` action.

---

q2_moshpit/assets/busco/index.html
q2_moshpit/busco/tests/data/plot_as_dict.json
q2_moshpit/busco/tests/test_utils.py
q2_moshpit/busco/utils.py

This reverts commit 1e9cc2c83f336b7ddb3c6f73978152de6f603055. This issue will be addressed again in a later PR.

Revert "BUG: allow sample filtering in evaluate-busco qzv (#142)"

---

q2_moshpit/eggnog/__init__.py
q2_moshpit/eggnog/_method.py
q2_moshpit/eggnog/tests/test_method.py
q2_moshpit/partition/__init__.py
q2_moshpit/partition/ortholog.py
q2_moshpit/plugin_setup.py

Adds support for parallelization of the `eggnog-annotate` action.

ENH: parallelize `eggnong-annotate`

---

q2_moshpit/plugin_setup.py

The description for inputs and outputs was missing in `eggnog-annotate`. Similarly the description of the outputs was missing in `eggnog-diamond-search`. This PR adds said descriptions.

MAINT: complete the description of inputs and outputs in `eggnog-annotate` and `eggnog-diamond-search`

---

setup.py

hey @misialq! looks like this test data dir was missing from the package data - this was our only test failure in the metagenome prepare PR (link [here](https://github.com/qiime2/distributions/actions/runs/9175496269/job/25337187346?pr=249#step:9:268)), so once this gets merged we should have a passing prepare! 🙂

BUG: add mags-derep test dir to package_data

---

setup.py

`test_busco_feature_data.py::TestBUSCOFeatureData::test_evaluate_busco_action` and `test_busco_sample_data.py::TestBUSCOSampleData::test_evaluate_busco_action` failing because test data is missing. This PR includes such data by specifying it in the `setup.py`.

TEST: include missing busco test files

---

.github/workflows/ci.yaml

This PR updates Python version to 3.9 in our "Test" CI, following the recent update in the QIIME 2 distros.

MAINT: update Python version in test CI

---

q2_moshpit/kraken2/select.py
q2_moshpit/kraken2/tests/data/mag-taxa-5.csv
q2_moshpit/kraken2/tests/test_selection.py

Closes #179.
When a MAG has a mix of bacterial and eukaryotic contigs our LCA selection marks those taxonomies as NaN, while they probably should just be labeled as "d__Unclassified" (otherwise, other actions, like taxa barplot, fail as they can't handle those NaNs).

FIX: correctly label 'Unclassfied' MAGs in the respective taxonomy

---

q2_moshpit/kaiju/database.py
q2_moshpit/kaiju/tests/test_database.py
q2_moshpit/plugin_setup.py

Closes #197.
To test, execute the action with a DB of choice (`viruses`, `plasmids` or `fungi` are some good, small DBs to try):
```
qiime moshpit fetch-kaiju-db \
--p-database-type<db type> \
--o-database db.qza \
--verbose
```

FIX: update how fetch-kaiju-db action discovers DB URLs

---

ci/recipe/meta.yaml

Hey @misialq - I'm working on getting a solved metagenome environment for the python 3.10 update, and it looks like we'll have to bump the current version of `busco`. I did a bit of digging, and it looks like the reason for this pin came from the older `biopython` pin that was in assembly (that had to be removed for the python 3.9 update). I'm opening this paired PR so that I can test this change over in distributions, but this change won't need to go into effect until we get a solved metapackage with passing tests. So it can just be left as-is for now! I'll circle back with updates as I have them.

LANG: relax busco pin for python 3.10 update

---

.github/workflows/ci.yaml
q2_moshpit/kraken2/tests/test_bracken.py
q2_moshpit/kraken2/tests/test_database.py

This PR:
- fixes mamba version used by the setup_miniconda to 1.5.10 to prevent CI failures cause by mamba 2.0.0
- updates paths to some test files

CI: fix mamba version and some test file paths

---

.github/workflows/ci-dev.yaml
.github/workflows/q2-ci.yaml
ci/recipe/meta.yaml

We will not test coverage when running QIIME 2 CI. This will only happen in one place, which is our other CI workflow (ci.yaml).

CI: remove coverage testing from Q2 CI

---

.github/workflows/ci-dev.yaml
.github/workflows/ci.yaml
.github/workflows/q2-ci.yaml
README.md
pyproject.toml

This PR fixes a typo in the path where the version file will be written to when the python package is built. This ensures that the correct version will be present when running 'qiime info' via the cli.

BUG: fix path in version file

---

q2_annotate/kraken2/bracken.py
q2_annotate/kraken2/tests/test_bracken.py
q2_annotate/plugin_setup.py
setup.cfg

This PR removes the `estimate-bracken` action registration from plugin_setup.py in case the detected OS is OSX. The reason for this behaviour is the unavailability of Bracken on OSX platform - we don't want the users to run into weird erros.
More details in [this](https://forum.qiime2.org/t/bracken-command-not-found/32164/12) forum post.

FIX: make the estimate-bracken action unavailable on OSX

---

q2_annotate/kraken2/database.py
q2_annotate/plugin_setup.py

Adds ability to fetch the [GTDB (genomic_files_reps)](https://benlangmead.github.io/aws-indexes/k2) Kraken2 database.

ENH: add ability to fetch gtdb to build_kraken_db

---

q2_annotate/busco/busco.py
q2_annotate/busco/tests/test_busco_feature_data.py
q2_annotate/busco/tests/test_busco_sample_data.py
q2_annotate/busco/tests/test_utils.py
q2_annotate/busco/utils.py

closes #256 
- Adds helper function `_validate_parameters` that raises error with message if parameters lineage_dataset, auto_lineage, auto_lineage_euk and  auto_lineage_prok are all None.

ENH: add validation that a lineage dataset or auto lineage is specified

---

q2_annotate/busco/busco.py
q2_annotate/busco/tests/test_busco_feature_data.py
q2_annotate/busco/tests/test_busco_sample_data.py

FIX: pass the arguments to _process_busco_results in the correct order

---

q2_annotate/kraken2/select.py

BUG: fix unnecessary failure when non-species infraclade tip is found  and not inserted
